twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'

when@test:
    twig:
        strict_variables: true
