vich_uploader:
    db_driver: orm

    mappings:
        profile_pictures:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer