#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /deconnexion
    methods: GET
#outing_list_places:
 #   path:     sortir.com/public/api/town/{idTown}/places
  #  defaults: { _controller: "App:OutingCreationController:listPlacesOfTownAction" }
   # methods:  GET